name: Build and Deploy to GitHub Pages

# 触发机制
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -f ./Dockerfile.dev -t nextjs14cicd:latest .

      - name: Save Docker image as tar
        run: docker save nextjs14cicd:latest > nextjs14cicd.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: nextjs14cicd.tar

      - name: Deploy to remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          # Download Docker image tar from the artifact
          mkdir -p $HOME/docker
          cd $HOME/docker
          curl -LO ${{ steps.upload-artifact.outputs.download-url }}

          # Copy Docker image tar to remote server
          scp -i $SSH_PRIVATE_KEY my-image.tar $REMOTE_USER@$REMOTE_HOST:/tmp

          # SSH into remote server and deploy
          ssh -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST << 'EOF'
            # Load Docker image
            docker load -i /tmp/my-image.tar

            # Stop and remove old container if it exists
            docker stop my-container || true
            docker rm my-container || true

            # Run new container
            docker run -d --name my-container my-image:latest
          EOF
